DOMAIN = "meteo_system_weather"

CONF_STATION_NAME = "station_name"
CONF_WEATHER_STATIONS = "weather_stations"

ATTR_LAST_UPDATE = "last_update"
ATTR_TEMP = "temperature"
ATTR_HUMIDITY = "humidity"
ATTR_PERCEIVED_TEMP = "perceived"
ATTR_TEMP_STATUS = "temp_status"
ATTR_PRESSURE = "pressure"
ATTR_WIND = "wind"
ATTR_WIND_DIRECTION = "wind_direction"
ATTR_WIND_STATUS = "wind_status"
ATTR_RAIN = "rain"
ATTR_RAIN_STATUS = "rain_status"
ATTR_RAIN_INTENSITY = "rain_intensity"
ATTR_STATION_STATUS = "station_status"
